apiVersion: v2
name: budget-app-backend
description: A Helm chart for the budget API backend
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 16.6.6
    repository: https://charts.bitnami.com/bitnami
