{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "budget-api.fullname" . }}-env
  labels:
    {{- include "budget-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
