import { StyleSheet, type TextStyle } from 'react-native';
import { colors, spacing, radius, typography, glassEffects } from '@/utils/design-system';

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  flex1: { flex: 1 },
  railWrap: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
  },
  rail: { flexDirection: 'row', gap: spacing.xs, height: 4 },
  railSeg: { flex: 1, borderRadius: radius.full },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xl,
    marginBottom: spacing.md,
  },
  headerSide: { width: 64, alignItems: 'flex-start', justifyContent: 'center' },
  headerSideRight: { alignItems: 'flex-end' },
  headerSpacer: { width: 40, height: 40 },
  headerTitle: { flex: 1, textAlign: 'center', color: colors.text, ...typography.bodyBold },
  skipHeaderText: { color: colors.primary2, ...typography.smallBold },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.xxl,
    justifyContent: 'center',
  },
  stepContent: { alignItems: 'stretch', paddingVertical: spacing.lg },
  welcomeContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xxl,
  },
  ctaWrapper: {
    width: '100%',
    borderRadius: radius.lg,
    overflow: 'hidden',
    marginTop: spacing.md,
  },
  ctaDisabled: { opacity: 0.5 },
  cta: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xl,
    borderRadius: radius.lg,
  },
  ctaText: { color: colors.text, ...typography.button },
  ghostCta: {
    ...glassEffects.glass,
    marginTop: spacing.md,
    minHeight: 48,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  ghostCtaText: { color: colors.text, ...typography.button },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.lg,
    marginTop: spacing.md,
    backgroundColor: `${colors.success}1f`,
    borderWidth: 1,
    borderColor: `${colors.success}33`,
  },
  statusPillText: { color: colors.success, ...typography.smallBold },
  noticeCard: {
    ...glassEffects.glass,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
    marginTop: spacing.md,
  },
  noticeText: { flex: 1, color: colors.text, ...typography.small },
  noticeRetry: { color: colors.primary2, ...typography.smallBold },
  fieldWrap: { width: '100%', marginTop: spacing.lg },
  fieldLabel: { color: colors.textMuted, ...typography.caption, marginBottom: spacing.xs },
  fieldInput: {
    ...glassEffects.glass,
    minHeight: 48,
    borderRadius: radius.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    color: colors.text,
    ...typography.body,
  } as TextStyle,
  fieldInputDisabled: { opacity: 0.6 },
  glassCard: { ...glassEffects.glass, padding: spacing.lg, width: '100%' },
  cardBody: { color: colors.textMuted, ...typography.small, marginBottom: spacing.sm },
  helper: { color: colors.textMuted, ...typography.caption },
  orbsContainer: { width: 160, height: 120, marginBottom: spacing.xl, position: 'relative' },
  orb: { width: 100, height: 100, borderRadius: radius.full, position: 'absolute', top: 10 },
  wordmarkRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.xl },
  wordmarkCouple: { ...typography.h1 },
  wordmarkFlow: { ...typography.h1 },
  wordmarkHeartGlyph: { fontSize: 28, marginHorizontal: spacing.xs },
  headline: {
    color: colors.text,
    ...typography.h3,
    textAlign: 'center',
    maxWidth: 320,
    marginBottom: spacing.sm,
  },
  headlineLeft: { color: colors.text, ...typography.h3, marginBottom: spacing.sm },
  subtitle: {
    color: colors.textMuted,
    ...typography.body,
    textAlign: 'center',
    marginBottom: spacing.xl,
  },
  welcomeCtaWrap: { width: '100%', marginTop: spacing.lg },
  skipLink: { alignSelf: 'center', marginTop: spacing.lg, padding: spacing.sm },
  skipLinkText: { color: colors.primary2, ...typography.smallBold },
  expenseRow: {
    ...glassEffects.glass,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    marginTop: spacing.sm,
    borderRadius: radius.md,
  },
  expenseRowOff: { opacity: 0.55 },
  expenseName: { flex: 1, color: colors.text, ...typography.smallBold },
  expenseAmt: { color: colors.textMuted, ...typography.small },
  providerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  providerPill: {
    ...glassEffects.glass,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.full,
  },
  providerPillOn: {
    borderColor: colors.primary2,
    backgroundColor: 'rgba(124,58,237,0.25)',
  },
  providerPillText: { color: colors.text, ...typography.smallBold },
  summaryChips: {
    ...glassEffects.glass,
    marginTop: spacing.md,
    padding: spacing.md,
    borderRadius: radius.md,
  },
  summaryChipText: { color: colors.textMuted, ...typography.small },
  roadmapCard: { ...glassEffects.glass, padding: spacing.lg, width: '100%', marginTop: spacing.md },
  roadmapItem: { flexDirection: 'row', gap: spacing.lg },
  roadmapLeft: { alignItems: 'center' },
  levelChip: {
    width: 40,
    height: 40,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  connector: {
    width: 2,
    flex: 1,
    minHeight: spacing.xl,
    backgroundColor: colors.borderGlass,
    marginVertical: spacing.xs,
  },
  roadmapRight: { flex: 1, paddingTop: spacing.xs, paddingBottom: spacing.lg },
  levelTitle: { color: colors.text, ...typography.smallBold, marginBottom: spacing.xs },
  levelDesc: { color: colors.textMuted, ...typography.caption },
  centerCard: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xxxl,
    gap: spacing.md,
  },
  centerTitle: { color: colors.text, ...typography.h3, textAlign: 'center', marginTop: spacing.sm },
  centerBody: { color: colors.textMuted, ...typography.body, textAlign: 'center', maxWidth: 300 },
  centerCtaWrap: { width: '100%', marginTop: spacing.lg },
});
